[window]
padding = {x = 2, y = 2}

[font]
size = 8.0
normal = { family = "JetBrains Mono", style = "Regular" }

[[keyboard.bindings]]
key = "."
mods = "Alt"
chars = "\u001b."

[[keyboard.bindings]]
key = "k"
mods = "Command"
chars = "\u001b[999~"
