;;; nasm-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nasm-mode.el

(autoload 'nasm-mode "nasm-mode" "\
Major mode for editing NASM assembly programs.

(fn)" t)
(register-definition-prefixes "nasm-mode" '("nasm-"))

;;; End of scraped data

(provide 'nasm-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nasm-mode-autoloads.el ends here
